"""empty message

Revision ID: 34607e5c318f
Revises: 1fd6ada5aa64
Create Date: 2023-08-10 10:27:29.848832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34607e5c318f'
down_revision = '1fd6ada5aa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.drop_constraint('user_match_match_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['match_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_match_match_id_fkey', 'users', ['match_id'], ['id'])

    # ### end Alembic commands ###
