"""empty message

Revision ID: 3a8d569b3c59
Revises: 511b721b525b
Create Date: 2023-07-24 18:41:30.036215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a8d569b3c59"
down_revision = "511b721b525b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("is_paused", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("is_band", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column(
            "is_authenticated", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column(
            "is_anonymous", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_anonymous", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "is_authenticated", existing_type=sa.BOOLEAN(), nullable=True
        )
        batch_op.alter_column("is_band", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_paused", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_admin", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
