"""empty message

Revision ID: 511b721b525b
Revises: 38d2c698add5
Create Date: 2023-07-24 18:36:47.457262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "511b721b525b"
down_revision = "38d2c698add5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_paused", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("is_authenticated", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("is_anonymous", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_anonymous")
        batch_op.drop_column("is_authenticated")
        batch_op.drop_column("is_paused")

    # ### end Alembic commands ###
