"""empty message

Revision ID: 55c3341bd25e
Revises: 34607e5c318f
Create Date: 2023-08-10 10:28:40.355653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c3341bd25e'
down_revision = '34607e5c318f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_profile', schema=None) as batch_op:
        batch_op.drop_constraint('match_profile_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.drop_constraint('user_match_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_match_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('match_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('match_profile_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
