"""empty message

Revision ID: 5abb22103a69
Revises: 8cba930032f1
Create Date: 2023-08-02 22:14:39.079327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abb22103a69'
down_revision = '8cba930032f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.drop_column('is_invited')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_invited', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
