"""empty message

Revision ID: 6f843f9b377f
Revises: 5abb22103a69
Create Date: 2023-08-02 23:15:11.757352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f843f9b377f'
down_revision = '5abb22103a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.alter_column('is_accepted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
