"""empty message

Revision ID: 79425d08f57d
Revises: c1676adfbbad
Create Date: 2023-07-04 11:50:54.757417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79425d08f57d"
down_revision = "c1676adfbbad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_token", schema=None) as batch_op:
        batch_op.alter_column(
            "granted_at",
            existing_type=sa.INTEGER(),
            type_=sa.DateTime(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auth_token", schema=None) as batch_op:
        batch_op.alter_column(
            "granted_at",
            existing_type=sa.DateTime(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
