"""empty message

Revision ID: 7c8bbf6a7b16
Revises: e2823c4be62b
Create Date: 2023-08-09 09:07:32.298423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8bbf6a7b16'
down_revision = 'e2823c4be62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
