"""empty message

Revision ID: 8119d3e31d7a
Revises: 79425d08f57d
Create Date: 2023-07-22 09:20:38.464820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8119d3e31d7a"
down_revision = "79425d08f57d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint("message_user_fk", type_="foreignkey")
        batch_op.drop_column("recipient_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("recipient_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "message_user_fk",
            "users",
            ["recipient_id"],
            ["id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
