"""empty message

Revision ID: 88664026b22b
Revises: 33878983233b
Create Date: 2023-08-10 10:24:14.943741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88664026b22b'
down_revision = '33878983233b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_profile', schema=None) as batch_op:
        batch_op.drop_constraint('match_profile_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.NUMERIC(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('match_profile', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('match_profile_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
