"""empty message

Revision ID: 8cba930032f1
Revises: 9a9f5e64eeb8
Create Date: 2023-08-02 22:03:57.131865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cba930032f1'
down_revision = '9a9f5e64eeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_invited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')
        batch_op.drop_column('is_invited')

    # ### end Alembic commands ###
