"""empty message

Revision ID: 9a9f5e64eeb8
Revises: 3a8d569b3c59
Create Date: 2023-07-31 21:08:07.681143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9f5e64eeb8'
down_revision = '3a8d569b3c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.drop_constraint('user_band_band_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['band_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_band_band_id_fkey', 'band', ['band_id'], ['id'])

    # ### end Alembic commands ###
