"""empty message

Revision ID: b56e443f473e
Revises: bed092266ed8
Create Date: 2023-08-04 15:30:32.291720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56e443f473e'
down_revision = 'bed092266ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.alter_column('seen',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.alter_column('seen',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
