"""empty message

Revision ID: bed092266ed8
Revises: 6f843f9b377f
Create Date: 2023-08-04 15:26:20.435090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed092266ed8'
down_revision = '6f843f9b377f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_band', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
