"""empty message

Revision ID: d63a1bf01223
Revises: 
Create Date: 2023-06-29 08:48:23.289054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d63a1bf01223"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_band", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("users")
    op.drop_table("bands")
    op.drop_table("roles")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("pkid", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("role_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("pkid", name="roles_pkey"),
    )
    op.create_table(
        "bands",
        sa.Column("pkid", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("band_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("genre", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("members", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("pkid", name="bands_pkey"),
    )
    op.create_table(
        "users",
        sa.Column("pkid", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("first_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_band", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("pkid", name="users_pkey"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###
