"""empty message

Revision ID: e4ea06fdf5c8
Revises: 8119d3e31d7a
Create Date: 2023-07-22 09:44:27.390998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4ea06fdf5c8"
down_revision = "8119d3e31d7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_message_group_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            None, "user_message_group", ["user_message_group_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_message_group_id")

    # ### end Alembic commands ###
