# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Rockr

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: | 
        echo ${{secrets.SETTINGS}} | base64 -d > rockr/settings.py
        pytest -v --cov=rockr tests
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_KEY  }}
            HOSTNAME : ${{ secrets.EC2_DOMAIN  }}
            USER_NAME : ${{ secrets.EC2_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > rockr-server.pem && chmod 400 rockr-server.pem
          ssh -o StrictHostKeyChecking=no -i rockr-server.pem ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /etc/rockr/rockr-server &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master
            pip install -r requirements.txt
            
            